name: MVRBind
channels:
  - pytorch
  - https://conda.anaconda.org/nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - blas=2.132
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.9pip freeze > requirements.txt
  - certifi=2025.7.9
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - filelock=3.18.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - intel-openmp=2024.2.1
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2024.10.24
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.50
  - libsqlite=3.50.2
  - libtiff=4.7.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - mkl-devel=2024.2.2
  - mkl-include=2024.2.2
  - mpmath=1.3.0
  - networkx=3.4.2
  - opencl-headers=2025.06.13
  - openjpeg=2.5.3
  - openssl=3.5.1
  - pillow=11.3.0
  - pip=25.1.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.18
  - python_abi=3.10
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.4
  - setuptools=80.9.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.85
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - multidict==6.6.3
      - numpy==1.23.5
      - packaging==25.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - six==1.17.0
      - threadpoolctl==3.6.0
      - torch-cluster==1.6.3+pt22cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt22cu121
      - torch-sparse==0.6.18+pt22cu121
      - torch-spline-conv==1.2.2+pt22cu121
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.1
      - yarl==1.20.1
